#!/usr/bin/env python

import argparse
import logging

from gevent.server import StreamServer
from feedback import MockFeedback
from gateway import MockGateway

DEFAULT_GATEWAY_PORT = 2195
DEFAULT_FEEDBACK_PORT = 2196

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Mock APNS Service")
    parser.add_argument('--debug', action='store_true', help='Print debug messages')
    parser.add_argument('--cert', type=str, required=True, help="Absolute path to the certificate file")
    parser.add_argument('--gatewayPort', type=int, default=DEFAULT_GATEWAY_PORT, help="Absolute path to the certificate file")
    parser.add_argument('--feedbackPort', type=int, default=DEFAULT_FEEDBACK_PORT, help="Absolute path to the certificate file")

    args = parser.parse_args()

    log_level = 'DEBUG' if args.debug else 'INFO'
    logging.basicConfig(level=log_level)

    certPath = args.cert

    gateway = MockGateway()
    feedback = MockFeedback(gateway.feedback)

    gatewayPort = args.gatewayPort
    feedbackPort = args.feedbackPort

    gateway_server = StreamServer(('0.0.0.0', gatewayPort), gateway, keyfile=certPath, certfile=certPath)
    feedback_server = StreamServer(('0.0.0.0', feedbackPort), feedback, keyfile=certPath, certfile=certPath)

    try:
        logging.info("Starting Feedback service listening on %s" % feedbackPort)
        feedback_server.start()
        logging.info("Starting APNS service listening on port %s" % gatewayPort)
        gateway_server.serve_forever()
    finally:
        logging.info("Shutting down")
        gateway_server.stop()
        feedback_server.stop()
